version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
         - | touch .env
            echo "${{secrets.PROD_ENV_FILE}}" > .env
            npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
