name: 🚀 new-dev-runner

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4

