name: Scheduled Workflow

on:
  schedule:
    - cron: '3 13 * * *' # Runs every day at 12 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Specify a version
      - run: npm install
      - run: npm test

